apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockservice
spec:
  selector:
    matchLabels:
      app: stockservice
      version: v1
  template:
    metadata:
      labels:
        app: stockservice
        version: v1
    spec:
      containers:
        - name: stockservice-container
          image: 01386/estock-stock:v1
          env:
            - name: MONGO_USER
              value: "root"
            - name: MONGO_PASSWORD
              value: "admin123"     
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@stockdb-service:27017"
            - name: MONGO_DATABASE_NAME
              value: "StockDB"
            - name: RABBIT_HOST
              value: "my-release-rabbitmq"
            - name: RABBIT_ADD_COMPANY_QUEUE
              value: "newcustomer" 
            - name: RABBIT_DELETE_COMPANY_QUEUE
              value: "deletecustomer" 
            - name: RABBIT_ADD_STOCK_QUEUE
              value: "addstock" 
            - name: RABBIT_USERNAME
              value: "user" 
            - name: RABBIT_PASSWORD
              value: "RIZJiYYMcH"
            - name: ELASTIC_URL
              value: "http://elk-service:9200"               
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 80