apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      app: userservice
      version: v1
  template:
    metadata:
      labels:
        app: userservice
        version: v1
    spec:
      containers:
        - name: userservice-container
          image: 01386/estock-user:v1
          env:                        
            - name: SQL_HOST
              value: "userdb-service,1433"
            - name: SQL_DB
              value: "usersDB"
            - name: SQL_INTEGRATED_SECURITY
              value: "N"
            - name: SQL_USER
              value: "SA"
            - name: SQL_PASSWORD
              value: "DZgE9tmQeHZxFDOpHWEm"
            - name: ELASTIC_URL
              value: "http://elk-service:9200"                                        
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
            