apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    # broker: kafka-server
    config: kafka
  name: kafka
data:
  KAFKA_ADVERTISED_HOST_NAME: kafka-service
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_ADVERTISED_PORT: "9092"
