#create secret with username and password, which has to be accessed in ASP.NET Core API
#for assigning values to secret keys use base64 format,
#for example run command in terminal `echo -n 'root' | base64` assign the result as value to key
apiVersion: v1
kind: Secret
metadata:
  name: userdb-secret
data:
  sqlsapassword: NX5pNDlkUDleSmxPMy5W