apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockservice
spec:
  selector:
    matchLabels:
      app: stockservice
      version: v1
  template:
    metadata:
      labels:
        app: stockservice
        version: v1
    spec:
      containers:
        - name: stockservice-container
          image: sukanyadas/stockservice:v1
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: stockdb-secret
                  key: dbuser
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stockdb-secret
                  key: dbpassword      
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@stockdb-service:27017"
            - name: MONGO_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: stock-config
                  key: dbname
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: stock-config
                  key: kafkahost
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: stock-config
                  key: kafkaport      
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 80