apiVersion: v1
kind: Service
metadata:
  labels:
    manager: zookeeper
  name: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    manager: zookeeper

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    manager: zookeeper
spec:
  template:
    metadata:
      labels:
        manager: zookeeper
    spec:
      hostname: zookeeper
      containers:
        - image: wurstmeister/zookeeper
          name: zookeeper
          ports:
            - containerPort: 2181
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      manager: zookeeper
