apiVersion: v1
kind: PersistentVolume
metadata:
  name: stockdb-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/stockdata"
  persistentVolumeReclaimPolicy: Retain