apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stockdb-pvc
spec:
  storageClassName: standard
  volumeName: stockdb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
