apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
spec:
  replicas: 1
  selector:
     matchLabels:
       app: userdb
  template:
    metadata:
      labels:
        app: userdb
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10001
      containers:
        - name: userdb-container
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userdb-secret
                  key: sqlsapassword
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: mssqldb-storage
              mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb-storage
        persistentVolumeClaim:
          claimName: mssql-data 
